# Change these first
owner: se-jaeger # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
assignees:
  - se-jaeger

sites:
  - name: sebastian-jaeger.me
    url: https://sebastian-jaeger.me
  - name: calgo-lab.de
    url: https://calgo-lab.de
  - name: mail.sebastian-jaeger.me
    url: https://mail.sebastian-jaeger.me
  - name: mail.jaegr.de
    url: https://mail.jaegr.de

status-website:
  introTitle: "Sebastian J채ger's Status & Uptime Monitoring"
  introMessage: This status page lists all services provided, hosted, and/or managed by Sebastian J채ger and checks their uptime every 5 minutes.
  cname: status.sebastian-jaeger.me
  baseUrl: /
  theme: dark
  name: Sebastian J채ger's Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://sebastian-jaeger.me

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"

commitMessages:
  commitAuthorName: "Sebastian J채ger (Bot)"
  commitAuthorEmail: "github@sebastian-jaeger.me"
